spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:mysql://j9a507.p.ssafy.io:3426/eagerbeaver
    username: EB
    password: kbsw2jEB!
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
  redis:
    host: j9a507.p.ssafy.io
    port: 6379

    properties:
      hibernate:
        format_sql: true
        show_sql: true

    defer-datasource-initialization: true   #-> data.sql을 사용하기 위해 추가

logging:
  level:
    com.ground.swm: INFO
    org.hibernate.SQL: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: INFO

# kakao 관련
kakao:
  rest-api-key: 45ea23576846eddff5204386c19df7b2
  #  redirect-uri: http://localhost:8080/api/auth/login # 백 테스트 전용
  #  redirect-uri: http://localhost:3000/nickname # application-local 전용
  redirect-uri: http://j9a507.p.ssafy.io/nickname # application-prod 전용

# 자체 jwt 관련
jwt:
  secret: eagerbeaversecretkeyhihellochillout